# Generated by Django 5.0 on 2024-01-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="slug",
            field=models.CharField(blank=True, max_length=128, verbose_name="Слаг"),
        ),
    ]
