# Generated by Django 5.0 on 2024-01-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_customuser_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="slug",
            field=models.CharField(max_length=128, unique=True, verbose_name="Слаг"),
        ),
    ]
