# Generated by Django 5.0 on 2024-01-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_followingusers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
    ]
