# Generated by Django 5.0 on 2024-02-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_customuser_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_online",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
