# Generated by Django 5.0 on 2024-02-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_customuser_last_interaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="last_interaction",
        ),
        migrations.AddField(
            model_name="customuser",
            name="time_online",
            field=models.IntegerField(
                default=0, verbose_name="Время онлайна пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_online",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последне время онлайна"
            ),
        ),
    ]
