# Generated by Django 5.0 on 2024-03-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="poster",
            field=models.ImageField(
                default="events_poster/default.jpg",
                upload_to="events_poster",
                verbose_name="Постер",
            ),
        ),
    ]
