repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
      - id: check-byte-order-marker
      - id: detect-private-key
      - id: check-ast
  - repo: 'https://github.com/PyCQA/flake8'
    rev: 3.8.2
    hooks:
      - id: flake8
  - repo: 'https://github.com/psf/black'
    rev: 22.3.0
    hooks:
      - id: black
        exclude: ^dist/
  - repo: 'https://github.com/Riverside-Healthcare/djLint'
    rev: v1.33.0
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v1.6.1
    hooks:
      - id: mypy
