# Generated by Django 5.0 on 2024-01-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_remove_word_transcription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(
                default="Default", max_length=128, verbose_name="Слаг"
            ),
        ),
        migrations.AddField(
            model_name="dictionarycourse",
            name="slug",
            field=models.SlugField(
                default="Default", max_length=128, verbose_name="Слаг"
            ),
        ),
        migrations.AddField(
            model_name="dictionarylesson",
            name="slug",
            field=models.SlugField(
                default="Default", max_length=128, verbose_name="Слаг"
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="slug",
            field=models.SlugField(
                default="Default", max_length=128, verbose_name="Слаг"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(
                default="Default", max_length=128, verbose_name="Слаг"
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="slug",
            field=models.SlugField(
                default="Default", max_length=128, verbose_name="Слаг"
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="slug",
            field=models.SlugField(
                default="Default", max_length=128, verbose_name="Слаг"
            ),
        ),
    ]
