# Generated by Django 5.0 on 2024-01-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_course_slug_dictionarycourse_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(max_length=128, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="dictionarycourse",
            name="slug",
            field=models.SlugField(max_length=128, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="dictionarylesson",
            name="slug",
            field=models.SlugField(max_length=128, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="slug",
            field=models.SlugField(max_length=128, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="slug",
            field=models.SlugField(max_length=128, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="module",
            name="slug",
            field=models.SlugField(max_length=128, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="word",
            name="slug",
            field=models.SlugField(max_length=128, verbose_name="Слаг"),
        ),
    ]
