# Generated by Django 5.0 on 2024-01-19 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0005_alter_exercise_answers_alter_exercise_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"verbose_name": "Ответ", "verbose_name_plural": "Ответы"},
        ),
        migrations.RemoveField(
            model_name="answer",
            name="question",
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="course.question",
                verbose_name="Вопрос",
            ),
        ),
    ]
