# Generated by Django 5.0 on 2024-01-22 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_alter_partoflesson_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(default=False, verbose_name="Правильный ответ"),
        ),
        migrations.AlterField(
            model_name="partoflesson",
            name="slug",
            field=models.CharField(
                choices=[
                    ("theory", "theory"),
                    ("practical", "practical"),
                    ("homework", "homework"),
                ],
                max_length=128,
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="partoflesson",
            name="title",
            field=models.CharField(
                choices=[
                    ("Теоретическая часть", "Теоретическая часть"),
                    ("Практическая часть", "Практическая часть"),
                    ("Домашняя работа", "Домашняя работа"),
                ],
                max_length=128,
                verbose_name="Название",
            ),
        ),
        migrations.CreateModel(
            name="PartOfLevelUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Пройден ли"),
                ),
                (
                    "part_of_lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts_of_lesson_user",
                        to="course.partoflesson",
                        verbose_name="Части урока",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts_of_lesson_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Части урока пользователя",
                "verbose_name_plural": "Части уроков пользователей",
            },
        ),
    ]
