# Generated by Django 5.0 on 2024-01-22 12:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0009_alter_answer_is_correct_alter_partoflesson_slug_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PartOfLevelUser",
            new_name="PartOfLessonUser",
        ),
    ]
