# Generated by Django 5.0 on 2024-03-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0011_moduleuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moduleuser",
            options={
                "verbose_name": "Модуль пользователя",
                "verbose_name_plural": "Модули пользователей",
            },
        ),
    ]
