# Generated by Django 5.0 on 2024-03-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0012_alter_moduleuser_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dictionarylesson",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="dictionarylesson",
            name="word",
        ),
        migrations.RemoveField(
            model_name="vocabularyuser",
            name="user",
        ),
        migrations.RemoveField(
            model_name="vocabularyuser",
            name="word",
        ),
        migrations.DeleteModel(
            name="DictionaryCourse",
        ),
        migrations.DeleteModel(
            name="DictionaryLesson",
        ),
        migrations.DeleteModel(
            name="VocabularyUser",
        ),
        migrations.DeleteModel(
            name="Word",
        ),
    ]
